---
title: "Annotation of IQTree tree from KR"
author: "A"
date: "4/5/2021"
output: html_document
---


## This is a one-time package installation to help get libraries likely to be missing at the start.

```{r eval=FALSE}
knitr::opts_chunk$set(error = TRUE)
#install needed packages
install.packages('BiocManager')# This option gave B errors; repos=c('https://cran.rstudio.com'), ask=F)
BiocManager::install('DECIPHER')
BiocManager::install("ggtree")
BiocManager::install("phytools")
tinytex::install_tinytex()
install.packages('BiocManager', repos=c('https://cran.rstudio.com'), ask=FALSE)
BiocManager::install('DECIPHER')
```

## Loading Libraries

```{r load-libraries, message=FALSE}
library(ggtree) # tree plotting
library(DECIPHER)
library(RCurl) # web page loading
library(phangorn)
library(phytools)
library(ape)
library("knitr")
library(DECIPHER)
library(treeio)

```
Fetch tree and metadata:
```{r}
cvx.metadata <- read.csv('../data/cvx_hostdata.csv', stringsAsFactors = FALSE)
cvx.newick.loc  <- "../data/iqtree-output/genbank_kr_consensus_extraction_al_trimmed.fasta.newick"
cvx.newick.tree <- read.newick(cvx.newick.loc)

```


Rename tips by comparing metadata file to $tip.names.
```{r tip-rename}
#create vector for host information
nj.gg <- reroot(cvx.newick.tree, node.number = 114)
hostinfo <- c()
hostinfo <- data.frame(nj.gg$tip.label)
#rename tree tips and populate vector
tip.rename.org = function(tree,dataframe){
   for(i in 1:length(tree$tip.label)){
      hostinfo$nj.gg.tip.label[i] <<- dataframe$host[grep(tree$tip.label[i],dataframe$Name)]
      #uncomment these for troubleshooting:
      #print(i)
      #print(tree$tip.label[i])
      #print(dataframe$Organism[grep(tree$tip.label[i],dataframe$Name)])
      tree$tip.label[i]<-dataframe$Organism[grep(tree$tip.label[i],dataframe$Name)]
        
   }
tree
}
```
Use renaming function:
```{r tip-rename-org}
nj.gg <- tip.rename.org(nj.gg,cvx.metadata)
```
Use plotted tree to select clade for pairwise analysis.
```{r}
plot.new()
nj.gg <- ladderize(nj.gg, right=FALSE)
plot(nj.gg,cex=0.25)
tips.store <- identify(nj.gg, nodes = TRUE, tips = TRUE,labels = FALSE, quiet = FALSE)$tips
#optional tip selection here, otherwise use tip numbers of desired clade
tips.cross <- c()
for (i in 1:length(tips.store)){
  print(nj.gg$tip.label[tips.store[i]])
  tips.cross[i] <- nj.gg$tip.label[tips.store[i]]
}
cross.data <- expand.grid(tip1 = tips.cross, tip2 = tips.cross)
```

```{r}
nj.gg <- groupClade(nj.gg, c(72,89,93,105,98,115))
cls <- list(c1=c("Cactus virus X: AF308158.2","SRR11190795 Plant: FR-3 NC_002815", "SRR11603184 GW-peel-1 NC_002815" ,"Plant DH-consensus 2 (2)","Plant GW-consensus 2 (2)","Plant BSJ-consensus 1 (3)" ,"15H5P__p_S54"  ,"SF19-1_sty_S45" ,"Plant 15H4,15H6-consensus(5)","15H3-consensus (3)","SRR11190793 Plant: BR-2 NC_002815","Plant RR-consensus 3 (5)","Cactus virus X: LC128411.1","Cactus virus X: KM365479.1","SRR11190796 Plant: FR-2 NC_002815", "SRR11190797 Plant: FR-1 NC_002815","SRR11190802 Plant: DH-1 NC_002815","SRR11190792 Plant: BR-3 NC_002815"),
            c2=c("Cactus virus X: JF937699.1", "Cactus virus X: SCM51431" ,"Cactus virus X: KM288847.1" ,"Cactus virus X: KM288846.1"),
            c3=c("Zygocactus virus X: Strain B1","Zygocactus virus X: KM288844.1_1","Zygocactus virus X-consensus (4)", "Plant RR-consensus 1 (5)","Plant DH,FR-consensus (5)"),
           # c4=c("Zygocactus virus X: KM288845.1_1"),
            c5=c("SRR11190795 Plant: FR-3 NC_024458","SRR11190801 Plant: DH-2 NC_024458","Pitaya virus X","Plant DH-consensus 3 (2)"  ,"SRR11603184 GW-peel-1 NC_024458","Plant GW-consensus 1 (2)"     ,"Plant BSJ-consensus 2 (3)","Plant BR-consensus (2)","Plant FR-consensus 2 (2)" , "Plant RR-consensus 2 (5)","Mytcor virus 1"),
c6=c("Schlumbergera virus X: Strain K11","Schlumbergera virus X: KP090203"  ,"SRR11190802 Plant: DH-1 NC_011659","Plant DH-consensus 1 (2)","Plant FR-consensus 1 (3)","SRR11603184 GW-peel-1 NC_011659"  ,"Plant RR-GW-consensus-3","Schlumbergera virus X: KU854929"  ),
c7=c("Opuntia virus: Strain CC10","Opuntia virus X: KU854931", "Opuntia virus X: KY348771")
  
)

```


Create image using ggtree. 

```{r fig.width=6, echo=F}
par( mar=c(1, 1, 0, 0))
L <- nj.gg$Nnode + length(nj.gg$tip.label)
ggtree(nj.gg, ladderize=T, aes(color=group), show.legend = FALSE, size=0.2)  %<+% hostinfo+
  theme(legend.position='none')+
  scale_color_manual(values=c("black","tomato", "royalblue", "chocolate","darkorchid4", "seagreen", "steelblue4")) +
  #name tip labels:
  geom_tiplab(aes(label=nj.gg$tip.label[1:L]), hjust=0, offset=0, align=T, linetype = "dotted")+
  #host tip labels:
  geom_tiplab(aes(label=hostinfo$nj.gg.tip.label[1:L]), align = T, linetype = 'blank', na.rm=TRUE, offset=0.3) +
  #scale
  geom_treescale(x=0, y=60, fontsize = 3) +
  #node labels:
  geom_text2(aes(subset = !isTip, label=label, hjust=-0.5)) +
  #geom_hilight(node=136, fill="steelblue", alpha=.6, extend=0.5)+
  xlim(0,2.2) +
#CLADE LABELS
geom_cladelabel(node=72, label="CVX Variant A", align=TRUE,  offset = .45, color='tomato') +
    geom_cladelabel(node=89, label="CVX Variant B", align=TRUE, offset = .45, color='royalblue') +
    geom_cladelabel(node=93, label="ZyVX Variant B1", align=TRUE, offset = .55, color='chocolate') +
      geom_strip("Zygocactus virus X: KM288845.1_1", "Zygocactus virus X: KM288845.1_1", label="ZyVX Variant A", align=TRUE, offset = .46, barsize=2, color='plum') +
      geom_cladelabel(node=105, label="Pitaya Virus X", align=TRUE, offset = .45, color='darkorchid4') +
      geom_cladelabel(node=98, label="Schlumbergera Virus X", align=TRUE, offset = .45, color='seagreen') +
      geom_cladelabel(node=115, label="Opuntia Virus X", align=TRUE,  offset = .45, color='steelblue4') +
  ggplot2::annotate("text", 0.2, 60.4, label="Substitutions per site")

```


Save the tree to folder in pdf format, if desired:
```{r eval=F}
filename = paste(gsub(":", "-", Sys.time()),"_bootstrap_tree.pdf",sep="")
ggsave(filename, width = 60, height = 40, units = "cm", limitsize = FALSE)
```

