---
title: "cvx.pairwise.analysis"
author: "A, B, K"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
> This is a one-time package installation to help get libraries likely to be missing at the start.

```{r eval=FALSE}
knitr::opts_chunk$set(error = TRUE)
#install needed packages
install.packages('BiocManager')# This option gave B errors; repos=c('https://cran.rstudio.com'), ask=F)
BiocManager::install('DECIPHER')
BiocManager::install("ggtree")
BiocManager::install("phytools")
tinytex::install_tinytex()
install.packages('BiocManager', repos=c('https://cran.rstudio.com'), ask=FALSE)
```

## Loading Libraries

```{r load-libraries, message=FALSE}
library(ggtree) # tree plotting
library(DECIPHER)
library(RCurl) # web page loading
library(phangorn)
library(phytools)
library(ape)
library("knitr")
library(DECIPHER)
```
##Analysis of viral pairwise distances
Load alignment.
```{r}
tre.f  <- "../data/iqtree-output/genbank_kr_consensus_extraction_al_trimmed.fasta.newick"
cvx.newick.tree <- read.newick(tre.f)

```

```{r}
cvx.metadata <- read.csv('../data/cvx_hostdata_v3.csv', stringsAsFactors = FALSE)
```



```{r tip-rename}
#create vector for host information (this is to insure that the vector is the right size -- tip labels will be overwritten)
hostinfo <- data.frame(cvx.newick.tree$tip.label)
#rename tree tips and populate vector
tip.rename.org = function(tree,dataframe){
   for(i in 1:length(tree$tip.label)){
      hostinfo$cvx.newick.tree.tip.label[i] <<- dataframe$host[grep(tree$tip.label[i],dataframe$Name)]
      #uncomment these for troubleshooting:
      #print(i)
      #print(tree$tip.label[i])
      #print(dataframe$Organism[grep(tree$tip.label[i],dataframe$Name)])
      tree$tip.label[i]<-dataframe$Organism[grep(tree$tip.label[i],dataframe$Name)]
        
   }
tree
}

#cvx.newick.tree <- midpoint.root(cvx.newick.tree)
cvx.newick.tree <- tip.rename.org(cvx.newick.tree, cvx.metadata)
```
Retrieve and store clade information for pairwise distances:
```{r}
choose.node <- function(col,tree) {
    o <- identify(tree)
    nodelabels(node=o$nodes, pch = 19, col = col)
    print(o)
}
plot.new()
cvx.newick.tree <- reroot(cvx.newick.tree, node.number = 114)
plot(cvx.newick.tree,cex=0.5)
identify(cvx.newick.tree, nodes = TRUE, tips = FALSE,labels = FALSE, quiet = FALSE)


```

```{r}
#create example list, or use your own for specific pairs. for all combos use dist.nodes(nj.gg)
data <- c("Virus from SRR11190799 Plant: BSJ-3", "Virus from SRR11190791 Plant: BSJ-1", "Virus from SRR11190800 Plant: BSJ-2")
data <- c("Virus from SRR11190798 Plant: DH-3", "Virus from SRR11190801 Plant: DH-2")
data <- c("Virus from SRR11603183 GW-peel-2", "Virus from SRR11603182 GW-peel-3")

cross.data <- expand.grid(tip1 = data, tip2 = data)
#cross.data <- expand.grid(tip1 = cvx.newick.tree$tip.label, tip2 = cvx.newick.tree$tip.label)

d<- c()
get.tree.dist = function(solcross.data,pathd8.tre)
{	
	for(i in 1:length(solcross.data$tip1))
	{
		ifelse(is.na(match(solcross.data$tip1[i],pathd8.tre$tip.label)) | is.na(match(solcross.data$tip2[i],pathd8.tre$tip.label)),d[i]<-NA,
		d[i]<-cophenetic.phylo(pathd8.tre)[solcross.data$tip1[i],solcross.data$tip2[i]])
	}
	return(d)
}
test <- get.tree.dist(cross.data,cvx.newick.tree)
test
mean(test[test!=0])
par( mar=c(2, 2, 2, 2))
heatmap(cophenetic.phylo(cvx.newick.tree), cexRow = 0.4, cexCol = 0.4)
```
