---
title: "bipartite"
author: "Alexa Tyszka"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/cactusvirusx/02_analyses/08_bipartite_figure/")
library(sna)
library(bipartite)
library(dplyr)
library(tidyr)
library(stringr)
library(igraph)
```


```{r setup-mptp-visweb}


metadata <- read.csv(file = "01_input/phylogeny_hosts.csv",header = TRUE)

metadata$df <- "df"
mdsub <- metadata[c("Formal.taxon", "mPTP", "bPTP", "df")]
mdfre <- subset(data.frame(table(mdsub)), Freq > 0)
md.web <- frame2webs(
  mdfre,varnames = 
    c( "bPTP","mPTP", "df", "Freq"), 
  type.out="list")

md.web2 <- frame2webs(
  mdfre,varnames = 
    c("mPTP",  "Formal.taxon","df", "Freq"), 
  type.out="list")

md.web.mPTP.bPTP <- frame2webs(
  mdfre,varnames = 
    c( "bPTP","mPTP", "df", "Freq"), 
  type.out="list")

dev.off()
pdf(file="02_output/web.mPTP.bPTP.pdf")
plot.new()
plotweb(md.web.mPTP.bPTP$df)

dev.off()
svg(file="02_output/web.mPTP.bPTP.svg")
plot.new()
plotweb(md.web.mPTP.bPTP$df)

dev.off()


svg(file="02_output/visweb.svg")
plot.new()
visweb(md.web.mPTP.bPTP$df)
dev.off()
pdf(file="02_output/visweb.pdf")
plot.new()
visweb(md.web.mPTP.bPTP$df)
dev.off()
```

```{r plotbigplot, out.extra='angle=0', fig.align = "center", echo=FALSE}
#https://cran.r-project.org/web/packages/bipartite/bipartite.pdf
plotweb2( md.web$df, md.web2$df,
            col.interaction = "lightgreen",
            col.interaction2 = "lightgreen",

)

pdf(file="02_output/bipartite_web.pdf")
plotweb2( md.web$df, md.web2$df,
            col.interaction = "lightgreen",
            col.interaction2 = "lightgreen",

)
dev.off()
svg(file="02_output/bipartite_web.svg")
par(mar=c(1,1,1,5))
#https://cran.r-project.org/web/packages/bipartite/bipartite.pdf
plotweb2( md.web$df, md.web2$df,
            col.interaction = "lightgreen",
            col.interaction2 = "lightgreen",

)
dev.off()

```
```{r bipartite-sp-host}
hostmetadata <- read.csv(file = "01_input/phylogeny_compare_hosts.csv",header = TRUE)

hg <- str_split_fixed(hostmetadata$host, " ", n = 2)
hg[,1]
hostmetadata$df <- "df"
hostmetadata$hostgenus <- hg[,1]
  hostmetadata$Formal.taxon[hostmetadata$Formal.taxon ==""] <-"Not assigned"
metadata$hostgenus[,1]
mdhostsub <- hostmetadata[c("Name", "Formal.taxon", "hostgenus", "df")]
mdhostfre <- subset(data.frame(table(mdhostsub)), Freq > 0)
mdhost.web <- frame2webs(
  mdhostfre, varnames = 
    c( "Formal.taxon", "hostgenus", "df", "Freq"), 
  type.out="list")

svg(file="02_output/hostxformalname.svg")
plot.new()
plotweb(mdhost.web$df)
dev.off()

pdf(file="02_output/hostxformalname.pdf")
plot.new()
plotweb(mdhost.web$df)
dev.off()

```

